# Akka-Cluster-Operator
#
scorecard:
  output: json
  plugins:
    - basic:
        cr-manifest:
          - "deploy/crds/app_v1alpha1_akkacluster_cr.yaml"
    - olm:
        cr-manifest:
          - "deploy/crds/app_v1alpha1_akkacluster_cr.yaml"
        csv-path: "deploy/olm-catalog/akka-cluster-operator/1.0.3/akka-cluster-operator.v1.0.3.clusterserviceversion.yaml"
