name: akkaclusteroperator-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      name: akka-cluster-operator
  template:
    metadata:
      labels:
        name: akka-cluster-operator
    spec:
      containers:
      - command:
        - akka-cluster-operator
        env:
        - name: WATCH_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.annotations['olm.targetNamespaces']
        - name: POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        - name: OPERATOR_NAME
          value: akka-cluster-operator
        image: lightbend-docker-registry.bintray.io/lightbend/akkacluster-operator:latest
        imagePullPolicy: Always
        name: akka-cluster-operator
        resources:
          limits:
            cpu: 200m
            memory: 100Mi
          requests:
            cpu: 100m
            memory: 50Mi
      serviceAccount: akka-cluster-operator
      serviceAccountName: akka-cluster-operator